const DATABASE_NAME = '@passkeeper';

const COLLECTION_USERS = `${DATABASE_NAME}:user`;
const COLLECTION_PASSWORDS = `${DATABASE_NAME}:password`;
const COLLECTION_THEMES = `${DATABASE_NAME}:theme`;

export {
  COLLECTION_USERS,
  COLLECTION_PASSWORDS,
  COLLECTION_THEMES
};