const DATABASE_NAME = '@passkeeper';

const COLLECTION_USERS = `${DATABASE_NAME}:user`;
const COLLECTION_PASSWORDS = `${DATABASE_NAME}:password`;

export {
  COLLECTION_USERS,
  COLLECTION_PASSWORDS
};